version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - ambassador-network

  user-service-mock:
    image: wiremock/wiremock:3.3.1
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/user-service:/home/wiremock
    command: >
      --global-response-templating
      --verbose
    networks:
      - ambassador-network

  product-service-mock:
    image: wiremock/wiremock:3.3.1
    ports:
      - "8082:8080"
    volumes:
      - ./wiremock/product-service:/home/wiremock
    command: >
      --global-response-templating
      --verbose
    networks:
      - ambassador-network

#  prometheus:
#    image: prom/prometheus:v2.45.0
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#      - '--web.console.templates=/usr/share/prometheus/consoles'
#      - '--web.enable-lifecycle'
#    networks:
#      - ambassador-network
#
#  grafana:
#    image: grafana/grafana:10.0.0
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - grafana-data:/var/lib/grafana
#      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
#      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
#    networks:
#      - ambassador-network

volumes:
  redis-data:
  grafana-data:

networks:
  ambassador-network:
    driver: bridge